import request from 'supertest';
import app from '../app';
import path from 'path';
import fs from 'fs';
import { chaosStore } from '../data/chaosStore';

describe('Profile and Avatar Upload API endpoints', () => {
  const dummyPngPath = path.resolve(__dirname, 'test-avatar.png');
  const dummyTxtPath = path.resolve(__dirname, 'test-file.txt');
  const largePngPath = path.resolve(__dirname, 'large-avatar.png');
  let authCookie: string;

  beforeAll(async () => {
    // 1. Create a dummy PNG file (a few bytes is enough to mock a PNG upload)
    fs.writeFileSync(dummyPngPath, 'mock-png-content-data');
    
    // 2. Create a dummy TXT file to verify format filtering
    fs.writeFileSync(dummyTxtPath, 'mock-txt-content-data');

    // 3. Create a large file (over 2MB) to verify size limit validation
    // 2.2 MB buffer
    const buffer = Buffer.alloc(2.2 * 1024 * 1024);
    fs.writeFileSync(largePngPath, buffer);

    // 4. Log in to obtain authenticated cookie session
    const res = await request(app)
      .post('/api/login')
      .send({ username: 'admin', password: 'password123' });
      
    const cookies = res.headers['set-cookie'] as unknown as string[];
    authCookie = cookies.find(c => c.startsWith('token='))!;
  });

  afterAll(() => {
    // Clean up temporary test files
    if (fs.existsSync(dummyPngPath)) fs.unlinkSync(dummyPngPath);
    if (fs.existsSync(dummyTxtPath)) fs.unlinkSync(dummyTxtPath);
    if (fs.existsSync(largePngPath)) fs.unlinkSync(largePngPath);

    // Clean up any uploaded files inside the uploads directory generated by these tests
    const uploadsDir = path.resolve(__dirname, '../../uploads');
    if (fs.existsSync(uploadsDir)) {
      const files = fs.readdirSync(uploadsDir);
      for (const file of files) {
        if (file.startsWith('admin-')) {
          fs.unlinkSync(path.join(uploadsDir, file));
        }
      }
    }
  });

  beforeEach(async () => {
    await request(app).post('/api/test/reset');
  });

  it('should return profile information for authenticated user', async () => {
    const res = await request(app)
      .get('/api/profile')
      .set('Cookie', [authCookie]);

    expect(res.status).toBe(200);
    expect(res.body.username).toBe('admin');
    expect(res.body.fullName).toBe('Admin User');
    expect(res.body).toHaveProperty('avatarUrl');
  });

  it('should upload valid PNG avatar image successfully', async () => {
    const res = await request(app)
      .post('/api/profile/upload')
      .set('Cookie', [authCookie])
      .attach('avatar', dummyPngPath);

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.avatarUrl).toContain('/uploads/admin-');
  });

  it('should reject avatar upload if file format is not image (e.g. TXT file)', async () => {
    const res = await request(app)
      .post('/api/profile/upload')
      .set('Cookie', [authCookie])
      .attach('avatar', dummyTxtPath);

    expect(res.status).toBe(400);
    expect(res.body.error).toContain('Only JPEG, JPG, and PNG images are allowed');
  });

  it('should reject avatar upload if file size exceeds 2MB limit', async () => {
    const res = await request(app)
      .post('/api/profile/upload')
      .set('Cookie', [authCookie])
      .attach('avatar', largePngPath);

    expect(res.status).toBe(400);
    expect(res.body.error).toContain('File size exceeds the 2MB limit');
  });

  it('should fail with 500 if uploadFailureRate chaos is set to 1.0', async () => {
    // 1. Enable 100% upload failure rate
    await request(app)
      .post('/api/test/config')
      .send({ uploadFailureRate: 1.0 });

    // 2. Upload avatar - should fail with 500
    const res = await request(app)
      .post('/api/profile/upload')
      .set('Cookie', [authCookie])
      .attach('avatar', dummyPngPath);

    expect(res.status).toBe(500);
    expect(res.body.error).toContain('Upload service failed');
  });

  it('should fail with 401 if unauthorized', async () => {
    const res = await request(app)
      .post('/api/profile/upload')
      .attach('avatar', dummyPngPath);

    expect(res.status).toBe(401);
  });
});
